# Generated by Django 3.2.10 on 2022-02-15 08:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bendungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provinsi', models.CharField(max_length=255, null=True)),
                ('kota', models.CharField(max_length=255, null=True)),
                ('balai', models.CharField(max_length=255, null=True)),
                ('bujur_x', models.FloatField(null=True)),
                ('lintang_y', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='gempa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('magnitude', models.FloatField()),
                ('depth', models.FloatField(null=True)),
                ('timetemp', models.CharField(max_length=25, null=True)),
                ('bujur_x', models.FloatField(null=True)),
                ('lintang_y', models.FloatField(null=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('estimasiradius', models.FloatField(null=True)),
                ('jumlahinf', models.IntegerField(null=True)),
                ('cluster', models.IntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='ipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provinsi', models.CharField(max_length=255, null=True)),
                ('kota', models.CharField(max_length=255, null=True)),
                ('bujur_x', models.FloatField(null=True)),
                ('lintang_y', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='iplt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provinsi', models.CharField(max_length=255, null=True)),
                ('kota', models.CharField(max_length=255, null=True)),
                ('bujur_x', models.FloatField(null=True)),
                ('lintang_y', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='jembatan_nasional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kode_jembatan', models.CharField(max_length=255, null=True)),
                ('panjang', models.FloatField(null=True)),
                ('lebar', models.FloatField(null=True)),
                ('nomor_jembatan', models.CharField(max_length=255, null=True)),
                ('bujur_x', models.FloatField(null=True)),
                ('lintang_y', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='rumah_khusus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provinsi', models.CharField(max_length=255, null=True)),
                ('kota', models.CharField(max_length=255, null=True)),
                ('alamat', models.CharField(max_length=255, null=True)),
                ('hunian', models.CharField(max_length=255, null=True)),
                ('bujur_x', models.FloatField(null=True)),
                ('lintang_y', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='rusunawa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provinsi', models.CharField(max_length=255, null=True)),
                ('kota', models.CharField(max_length=255, null=True)),
                ('alamat', models.CharField(max_length=255, null=True)),
                ('hunian', models.CharField(max_length=255, null=True)),
                ('bujur_x', models.FloatField(null=True)),
                ('lintang_y', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='spam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provinsi', models.CharField(max_length=255, null=True)),
                ('kota', models.CharField(max_length=255, null=True)),
                ('bujur_x', models.FloatField(null=True)),
                ('lintang_y', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='tpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provinsi', models.CharField(max_length=255, null=True)),
                ('kota', models.CharField(max_length=255, null=True)),
                ('bujur_x', models.FloatField(null=True)),
                ('lintang_y', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
