# Generated by Django 3.2.10 on 2022-04-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapgempa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mag_centroid', models.FloatField()),
                ('inf_centroid', models.FloatField()),
                ('jumlah', models.IntegerField()),
            ],
        ),
    ]
