# Generated by Django 3.2.10 on 2022-04-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapgempa', '0002_kluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='kluster',
            name='warna',
            field=models.CharField(default='#f54242', max_length=10),
            preserve_default=False,
        ),
    ]
