# Generated by Django 3.2.10 on 2022-05-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapgempa', '0003_kluster_warna'),
    ]

    operations = [
        migrations.AddField(
            model_name='gempa',
            name='normal_inf',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='gempa',
            name='normal_rad',
            field=models.FloatField(null=True),
        ),
    ]
